name: Build

on: [push]

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: jiro4989/setup-nim-action@v1

    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install webkit2gtk-4.0

    - name: Compile DEBUG Mode
      run: nim c -d:ssl --panics:on --styleCheck:hint --gc:arc src/webgui.nim

    - name: Compile RELEASE Mode
      run: nim c -d:release -d:danger -d:ssl --panics:on --styleCheck:hint --gc:arc src/webgui.nim
